### ISSUE TITLE
Is there an example?

### ISSUE THREAD

**Issue by delfinoA** [v7a/QOffice#1]
I'm wondering if there is an example,that I can know how to use QOffice in my project.

**Comment by NicolasKogler** [comment]
I am afraid there is not yet an example on how to use QOffice. It's not a problem to upload one by this evening, though. Please note that QOffice is not very advanced yet, because there are no widgets for it. But you can perfectly use the borderless window, which is fully functional, as a base!

**Comment by delfinoA** [comment]
Well,thanks for your advice, and your work on QOffice,too! I personally think QOffice is  very nice. I've read some code,and found it's pretty simple to use.

**Comment by NicolasKogler** [comment]
Thanks for the honor! I am really glad you figured how to use it. Nevertheless I should really provide an example soon, therefore I leave this issue open.
