### ISSUE TITLE
Compiler errors related to dllimport

### ISSUE THREAD

**Issue by Razzile** [v7a/QOffice#8]
Whenever I try to compile this project I get the following errors.
![image](https://user-images.githubusercontent.com/5256381/43213283-29ed4fdc-902e-11e8-8ecb-56caffef4f9f.png)

.sln is generated from a build folder inside the project root using `cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:\Qt\5.10.1\msvc2017_64" -DQOFFICE_BUILD_EXAMPLES=true ..`

**Comment by Razzile** [comment]
I managed to fix this by turning off shared libraries and also editing the Config.hpp file to move the following out of any #ifdefs because for some reason even though I chose to build static the project assumed I still wanted a shared library
```    
#define QOFFICE_CORE_API
#define QOFFICE_DESIGN_API
#define QOFFICE_WIDGET_API
#define QOFFICE_PLUGIN_API
```
This is obviously quite a hack so there's still something possibly misconfigured in the project

**Comment by v7a** [comment]
Alright, I now tested it with `-DQOFFICE_BUILD_SHARED=ON` and `-DQOFFICE_BUILD_SHARED=OFF` and both seem to work. @Razzile If you still encounter any issues, please leave a comment.
